-- Estación 1
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ABC123', 1, 1200, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'estacion_1'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 14:00', (SELECT id FROM Users WHERE username = 'estacion_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ789', 3, 2500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'estacion_1'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG456', 2, 1000, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'estacion_1'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-101', 1, 1100, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'estacion_1'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Estación 2
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ABC123', 1, 1500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'estacion_2'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 15:30', (SELECT id FROM Users WHERE username = 'estacion_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ789', 3, 3000, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'estacion_2'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG456', 2, 1200, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'estacion_2'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-102', 2, 1300, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'estacion_2'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Terpel Engativá
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('GHI789', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_engativa'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 10:00', (SELECT id FROM Users WHERE username = 'terpel_engativa'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('JKL012', 3, 3500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_engativa'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('MNO345', 2, 1500, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_engativa'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-103', 3, 1500, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_engativa'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Primax Alamos
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('PQR678', 1, 1800, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_alamos'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 11:20', (SELECT id FROM Users WHERE username = 'primax_alamos'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('STU901', 3, 2800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_alamos'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('VWX234', 2, 1100, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_alamos'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-104', 1, 1000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_alamos'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Texaco 80
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('YZA567', 1, 2200, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_80'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 16:45', (SELECT id FROM Users WHERE username = 'texaco_80'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('BCD890', 3, 4000, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_80'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG123', 2, 1800, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_80'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-105', 2, 1200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_80'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Mobil Quiriguá
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('HIJ456', 1, 1600, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_quirigua'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 09:15', (SELECT id FROM Users WHERE username = 'mobil_quirigua'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('KLM789', 3, 2600, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_quirigua'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('NOP012', 2, 1300, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_quirigua'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-106', 3, 2000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_quirigua'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Esso Villas
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('QRS345', 1, 1900, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_villas'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 12:30', (SELECT id FROM Users WHERE username = 'esso_villas'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('TUV678', 3, 3200, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_villas'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('WXY901', 2, 1400, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_villas'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-107', 1, 1600, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_villas'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Biomax 72
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ZAB234', 1, 1400, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_72'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 13:10', (SELECT id FROM Users WHERE username = 'biomax_72'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('CDE567', 3, 2400, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_72'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('FGH890', 2, 1000, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_72'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-108', 2, 1100, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'biomax_72'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Terpel Tabora
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('IJK123', 1, 1700, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_tabora'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 11:50', (SELECT id FROM Users WHERE username = 'terpel_tabora'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('LMN456', 3, 2900, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_tabora'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('OPQ789', 2, 1200, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_tabora'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-109', 3, 1800, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_tabora'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Primax Florida
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('RST012', 1, 1500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 15:10', (SELECT id FROM Users WHERE username = 'primax_florida'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('UVW345', 3, 2700, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ678', 2, 1100, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-110', 1, 1300, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Texaco Boyacá 80
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ABC901', 1, 2500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_boyaca_80'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 08:30', (SELECT id FROM Users WHERE username = 'texaco_boyaca_80'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('DEF234', 3, 4500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_boyaca_80'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('GHI567', 2, 2000, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_boyaca_80'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-111', 2, 1500, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_boyaca_80'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Mobil Florida
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('JKL890', 1, 1800, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 10:20', (SELECT id FROM Users WHERE username = 'mobil_florida'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('MNO123', 3, 3000, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('PQR456', 2, 1400, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-112', 3, 2100, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_florida'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Esso Garcés
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('STU789', 1, 2100, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_garces'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 13:45', (SELECT id FROM Users WHERE username = 'esso_garces'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('VWX012', 3, 3400, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_garces'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('YZA345', 2, 1600, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_garces'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-113', 1, 1900, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_garces'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Biomax Álamos Ind.
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('BCD678', 1, 2400, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_alamos_ind'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 16:15', (SELECT id FROM Users WHERE username = 'biomax_alamos_ind'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG901', 3, 3800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_alamos_ind'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('HIJ234', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_alamos_ind'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-114', 2, 1400, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'biomax_alamos_ind'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Terpel Bolivia
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('KLM567', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_bolivia'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 09:30', (SELECT id FROM Users WHERE username = 'terpel_bolivia'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('NOP890', 3, 3300, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_bolivia'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('QRS123', 2, 1500, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_bolivia'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-115', 3, 2300, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_bolivia'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Primax Cortijo
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('TUV456', 1, 2100, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_cortijo'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 11:45', (SELECT id FROM Users WHERE username = 'primax_cortijo'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('WXY789', 3, 3100, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_cortijo'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ZAB012', 2, 1600, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_cortijo'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-116', 1, 2000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_cortijo'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Texaco Serena
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('CDE345', 1, 2600, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_serena'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 14:15', (SELECT id FROM Users WHERE username = 'texaco_serena'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('FGH678', 3, 4200, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_serena'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('IJK901', 2, 2100, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_serena'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-117', 2, 1800, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_serena'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Mobil Boyacá 72
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('LMN234', 1, 1900, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_boyaca_72'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 12:00', (SELECT id FROM Users WHERE username = 'mobil_boyaca_72'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('OPQ567', 3, 3100, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_boyaca_72'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('RST890', 2, 1500, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_boyaca_72'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-118', 3, 2400, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_boyaca_72'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Esso Minuto
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('UVW123', 1, 2300, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_minuto'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 10:45', (SELECT id FROM Users WHERE username = 'esso_minuto'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ456', 3, 3600, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_minuto'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ABC789', 2, 1800, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_minuto'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-119', 1, 2100, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_minuto'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Biomax Eng. Centro
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('DEF012', 1, 1600, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_eng_centro'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 13:20', (SELECT id FROM Users WHERE username = 'biomax_eng_centro'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('GHI345', 3, 2600, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_eng_centro'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('JKL678', 2, 1300, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_eng_centro'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-120', 2, 1200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'biomax_eng_centro'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Terpel Estrada
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('MNO901', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_estrada'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 09:45', (SELECT id FROM Users WHERE username = 'terpel_estrada'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('PQR234', 3, 3300, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_estrada'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('STU567', 2, 1600, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_estrada'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-121', 3, 2200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_estrada'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Primax Santamaría
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('VWX890', 1, 2400, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_santamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 11:30', (SELECT id FROM Users WHERE username = 'primax_santamaria'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('YZA123', 3, 3800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_santamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('BCD456', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_santamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-122', 1, 2000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_santamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Texaco Bonanza
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('EFG789', 1, 2700, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_bonanza'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 15:45', (SELECT id FROM Users WHERE username = 'texaco_bonanza'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('HIJ012', 3, 4300, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_bonanza'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('KLM345', 2, 2200, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_bonanza'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-123', 2, 1900, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_bonanza'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Mobil Luján
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('NOP678', 1, 1900, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_lujan'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 16:30', (SELECT id FROM Users WHERE username = 'mobil_lujan'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('QRS901', 3, 3100, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_lujan'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('TUV234', 2, 1500, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_lujan'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-124', 3, 2300, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_lujan'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Esso Ferias
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('WXY567', 1, 2500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_ferias'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 09:00', (SELECT id FROM Users WHERE username = 'esso_ferias'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ZAB890', 3, 3900, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_ferias'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('CDE123', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_ferias'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-125', 1, 1800, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_ferias'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Biomax Boyacá 66
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('FGH456', 1, 1600, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_boyaca_66'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 11:20', (SELECT id FROM Users WHERE username = 'biomax_boyaca_66'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('IJK789', 3, 2600, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_boyaca_66'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('LMN012', 2, 1300, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_boyaca_66'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-126', 2, 1200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'biomax_boyaca_66'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Terpel Floridablanca
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('OPQ345', 1, 2100, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_floridablanca'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 14:45', (SELECT id FROM Users WHERE username = 'terpel_floridablanca'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('RST678', 3, 3400, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_floridablanca'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('UVW901', 2, 1700, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_floridablanca'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-127', 3, 2500, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_floridablanca'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Primax Villamaría
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('XYZ234', 1, 2300, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_villamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 10:10', (SELECT id FROM Users WHERE username = 'primax_villamaria'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ABC567', 3, 3600, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_villamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('DEF890', 2, 1800, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_villamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-128', 1, 1900, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_villamaria'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Texaco Sancayetano
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('GHI123', 1, 2800, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_sancayetano'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 13:30', (SELECT id FROM Users WHERE username = 'texaco_sancayetano'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('JKL456', 3, 4400, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_sancayetano'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('MNO789', 2, 2200, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_sancayetano'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-129', 2, 1800, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_sancayetano'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Mobil Bosque
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('PQR012', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_bosque'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 16:20', (SELECT id FROM Users WHERE username = 'mobil_bosque'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('STU345', 3, 3300, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_bosque'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('VWX678', 2, 1600, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_bosque'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-130', 3, 2200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_bosque'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Esso Real
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('YZA901', 1, 2500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_real'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 08:50', (SELECT id FROM Users WHERE username = 'esso_real'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('BCD234', 3, 3900, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_real'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG567', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_real'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-131', 1, 2000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_real'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Biomax Faena
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('HIJ890', 1, 1700, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_faena'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 11:40', (SELECT id FROM Users WHERE username = 'biomax_faena'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('KLM123', 3, 2800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_faena'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('NOP456', 2, 1400, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'biomax_faena'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-132', 2, 1200, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'biomax_faena'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));

-- Terpel Portal 80
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('QRS789', 1, 2200, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_portal80'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 14:30', (SELECT id FROM Users WHERE username = 'terpel_portal80'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('TUV012', 3, 3500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_portal80'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('WXY345', 2, 1700, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_portal80'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-133', 3, 2600, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'terpel_portal80'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));

-- Primax Zarzamora
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ZAB678', 1, 2400, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_zarzamora'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 16:50', (SELECT id FROM Users WHERE username = 'primax_zarzamora'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('CDE901', 3, 3800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_zarzamora'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('FGH234', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_zarzamora'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-134', 1, 2000, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'primax_zarzamora'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));

-- Texaco Boyacá 75
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('IJK567', 1, 2800, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'texaco_boyaca_75'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 09:20', (SELECT id FROM Users WHERE username = 'texaco_boyaca_75'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('LMN890', 3, 4400, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_boyaca_75'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('OPQ123', 2, 2200, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'texaco_boyaca_75'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-135', 2, 1700, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'texaco_boyaca_75'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));

-- Mobil Bachué
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('RST456', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'mobil_bachue'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 11:30', (SELECT id FROM Users WHERE username = 'mobil_bachue'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('UVW789', 3, 3300, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_bachue'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ012', 2, 1600, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'mobil_bachue'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-136', 3, 2100, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'mobil_bachue'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));

-- Esso Muelle
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ABC345', 1, 2500, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'esso_muelle'), (SELECT id FROM Users WHERE username = 'distribuidor_4'), '2026-03-16 13:50', (SELECT id FROM Users WHERE username = 'esso_muelle'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('DEF678', 3, 3900, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_muelle'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('GHI901', 2, 1900, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'esso_muelle'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-137', 1, 1800, '2026-03-19', 'ENTREGADO', (SELECT id FROM Users WHERE username = 'esso_muelle'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
