-- Precios para todas las estaciones (15 estaciones x 4 combustibles)
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15600, (SELECT id FROM Users WHERE username = 'terpel_zarzamora'), 1), (20800, (SELECT id FROM Users WHERE username = 'terpel_zarzamora'), 2), (9600, (SELECT id FROM Users WHERE username = 'terpel_zarzamora'), 3), (2600, (SELECT id FROM Users WHERE username = 'terpel_zarzamora'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15550, (SELECT id FROM Users WHERE username = 'eds_hergos_petrobras'), 1), (20750, (SELECT id FROM Users WHERE username = 'eds_hergos_petrobras'), 2), (9550, (SELECT id FROM Users WHERE username = 'eds_hergos_petrobras'), 3), (2550, (SELECT id FROM Users WHERE username = 'eds_hergos_petrobras'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15700, (SELECT id FROM Users WHERE username = 'terpel_engativa'), 1), (20900, (SELECT id FROM Users WHERE username = 'terpel_engativa'), 2), (9700, (SELECT id FROM Users WHERE username = 'terpel_engativa'), 3), (2650, (SELECT id FROM Users WHERE username = 'terpel_engativa'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15650, (SELECT id FROM Users WHERE username = 'biomax_inverniza'), 1), (20850, (SELECT id FROM Users WHERE username = 'biomax_inverniza'), 2), (9650, (SELECT id FROM Users WHERE username = 'biomax_inverniza'), 3), (2600, (SELECT id FROM Users WHERE username = 'biomax_inverniza'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15580, (SELECT id FROM Users WHERE username = 'eds_terpel_eldorado'), 1), (20780, (SELECT id FROM Users WHERE username = 'eds_terpel_eldorado'), 2), (9580, (SELECT id FROM Users WHERE username = 'eds_terpel_eldorado'), 3), (2580, (SELECT id FROM Users WHERE username = 'eds_terpel_eldorado'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15490, (SELECT id FROM Users WHERE username = 'shell_la_espanola'), 1), (20600, (SELECT id FROM Users WHERE username = 'shell_la_espanola'), 2), (9500, (SELECT id FROM Users WHERE username = 'shell_la_espanola'), 3), (2500, (SELECT id FROM Users WHERE username = 'shell_la_espanola'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15620, (SELECT id FROM Users WHERE username = 'terpel_av_boyaca'), 1), (20820, (SELECT id FROM Users WHERE username = 'terpel_av_boyaca'), 2), (9610, (SELECT id FROM Users WHERE username = 'terpel_av_boyaca'), 3), (2610, (SELECT id FROM Users WHERE username = 'terpel_av_boyaca'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15590, (SELECT id FROM Users WHERE username = 'eds_esso_quirigua'), 1), (20790, (SELECT id FROM Users WHERE username = 'eds_esso_quirigua'), 2), (9590, (SELECT id FROM Users WHERE username = 'eds_esso_quirigua'), 3), (2590, (SELECT id FROM Users WHERE username = 'eds_esso_quirigua'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15750, (SELECT id FROM Users WHERE username = 'primax_calle80_norte'), 1), (20950, (SELECT id FROM Users WHERE username = 'primax_calle80_norte'), 2), (9750, (SELECT id FROM Users WHERE username = 'primax_calle80_norte'), 3), (2680, (SELECT id FROM Users WHERE username = 'primax_calle80_norte'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15640, (SELECT id FROM Users WHERE username = 'primax_calle80_sur'), 1), (20840, (SELECT id FROM Users WHERE username = 'primax_calle80_sur'), 2), (9640, (SELECT id FROM Users WHERE username = 'primax_calle80_sur'), 3), (2620, (SELECT id FROM Users WHERE username = 'primax_calle80_sur'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15570, (SELECT id FROM Users WHERE username = 'eds_texaco_bloodberry'), 1), (20770, (SELECT id FROM Users WHERE username = 'eds_texaco_bloodberry'), 2), (9570, (SELECT id FROM Users WHERE username = 'eds_texaco_bloodberry'), 3), (2570, (SELECT id FROM Users WHERE username = 'eds_texaco_bloodberry'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15500, (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'), 1), (20650, (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'), 2), (9510, (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'), 3), (2520, (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15680, (SELECT id FROM Users WHERE username = 'terpel_calle49'), 1), (20880, (SELECT id FROM Users WHERE username = 'terpel_calle49'), 2), (9680, (SELECT id FROM Users WHERE username = 'terpel_calle49'), 3), (2640, (SELECT id FROM Users WHERE username = 'terpel_calle49'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15540, (SELECT id FROM Users WHERE username = 'eds_terpel_alamos'), 1), (20740, (SELECT id FROM Users WHERE username = 'eds_terpel_alamos'), 2), (9540, (SELECT id FROM Users WHERE username = 'eds_terpel_alamos'), 3), (2540, (SELECT id FROM Users WHERE username = 'eds_terpel_alamos'), 4);
INSERT OR IGNORE INTO Precios (precio, id_estacion, id_combustible) VALUES (15720, (SELECT id FROM Users WHERE username = 'primax_normandia'), 1), (20920, (SELECT id FROM Users WHERE username = 'primax_normandia'), 2), (9720, (SELECT id FROM Users WHERE username = 'primax_normandia'), 3), (2660, (SELECT id FROM Users WHERE username = 'primax_normandia'), 4);