-- Entregas para las 15 nuevas estaciones
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ABC123', 1, 1200, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'terpel_zarzamora'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 14:00', (SELECT id FROM Users WHERE username = 'terpel_zarzamora'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('XYZ789', 3, 2500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'eds_hergos_petrobras'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG456', 2, 1000, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_engativa'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('ENT-101', 1, 1100, '2026-03-19', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'biomax_inverniza'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-19 10:00', (SELECT id FROM Users WHERE username = 'biomax_inverniza'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('ENT-102', 2, 1300, '2026-03-19', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'eds_terpel_eldorado'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('GHI789', 1, 2000, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'shell_la_espanola'), (SELECT id FROM Users WHERE username = 'distribuidor_2'), '2026-03-16 10:00', (SELECT id FROM Users WHERE username = 'shell_la_espanola'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('JKL012', 3, 3500, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_av_boyaca'), (SELECT id FROM Users WHERE username = 'distribuidor_3'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('MNO345', 2, 1500, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'eds_esso_quirigua'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('PQR678', 1, 1800, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_calle80_norte'), (SELECT id FROM Users WHERE username = 'distribuidor_5'), '2026-03-16 11:20', (SELECT id FROM Users WHERE username = 'primax_calle80_norte'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('STU901', 3, 2800, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'primax_calle80_sur'), (SELECT id FROM Users WHERE username = 'distribuidor_1'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('VWX234', 2, 1100, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'eds_texaco_bloodberry'), (SELECT id FROM Users WHERE username = 'distribuidor_2'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('YZA567', 1, 2200, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'), (SELECT id FROM Users WHERE username = 'distribuidor_3'), '2026-03-16 16:45', (SELECT id FROM Users WHERE username = 'eds_texaco_lagranja'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('BCD890', 3, 4000, '2026-03-17', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'terpel_calle49'), (SELECT id FROM Users WHERE username = 'distribuidor_4'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id) VALUES ('EFG123', 2, 1800, '2026-03-18', 'PENDIENTE', (SELECT id FROM Users WHERE username = 'eds_terpel_alamos'), (SELECT id FROM Users WHERE username = 'distribuidor_5'));
INSERT OR IGNORE INTO Entregas (placa, id_combustible, cantidad, fecha, estado, estacion_destino_id, distribuidor_id, fecha_confirmacion, confirmado_por) VALUES ('HIJ456', 1, 1600, '2026-03-16', 'CONFIRMADO', (SELECT id FROM Users WHERE username = 'primax_normandia'), (SELECT id FROM Users WHERE username = 'distribuidor_1'), '2026-03-16 09:15', (SELECT id FROM Users WHERE username = 'primax_normandia'));